[project]
name = "vf-musique-rag"
version = "0.1.0"
dependencies = [
    "verifiers>=0.1.2",
    "requests>=2.31.0",
    "datasets>=2.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_musique_rag.py"] 